-- MySQL Script generated by MySQL Workbench
-- Fri Oct 15 17:06:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dietary_rec_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dietary_rec_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dietary_rec_app` DEFAULT CHARACTER SET utf8 ;
USE `dietary_rec_app` ;

-- -----------------------------------------------------
-- Table `dietary_rec_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietary_rec_app`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `birth_date` DATE NOT NULL,
  `weight` FLOAT NOT NULL,
  `height` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `usercol_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `dietary_rec_app`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietary_rec_app`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `carbohydrates` FLOAT NOT NULL,
  `proteins` FLOAT NOT NULL,
  `fat` FLOAT NOT NULL,
  `kcal` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `idproducts_UNIQUE` (`product_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dietary_rec_app`.`diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietary_rec_app`.`diet` (
  `diet_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `weight` FLOAT NOT NULL,
  PRIMARY KEY (`diet_id`),
  UNIQUE INDEX `diet_id_UNIQUE` (`diet_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dietary_rec_app`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `dietary_rec_app`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `dietary_rec_app` ;

-- -----------------------------------------------------
-- Placeholder table for view `dietary_rec_app`.`daily_diet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dietary_rec_app`.`daily_diet` (`date` INT, `username` INT, `product_name` INT, `weight` INT, `carbohydrates` INT, `proteins` INT, `fat` INT, `kcal` INT);

-- -----------------------------------------------------
-- View `dietary_rec_app`.`daily_diet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dietary_rec_app`.`daily_diet`;
USE `dietary_rec_app`;
CREATE  OR REPLACE VIEW `daily_diet` AS
select d.date, u.username, p.product_name, d.weight, p.carbohydrates, p.proteins, p.fat, p.kcal
from diet d
inner join user u on u.user_id=d.user_id
inner join product p on p.product_id=d.product_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
